- name: Create SDIMD issue via Jira Core API (workaround for Company validation)
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    project_key: "SDIMD"
    issuetype_id: "11301"          # Service Request

    urgency_id: "13518"            # Medium
    impact_id: "14612"             # Single user
    environment_id: "20707"        # Production
    reporting_service_key: "SD-215"
    company_name: "Emaratech"

  tasks:
    - name: Create Issue
      ansible.builtin.uri:
        url: "{{ jira_url }}/rest/api/2/issue"
        method: POST
        headers:
          Authorization: "Bearer {{ jira_pat }}"
          Content-Type: "application/json"
          Accept: "application/json"
        body_format: json
        body:
          fields:
            project:
              key: "{{ project_key }}"
            issuetype:
              id: "{{ issuetype_id }}"
            summary: "{{ summary }}"
            description: "{{ summary }}"

            # Company (required by your validator)
            customfield_20000: "{{ company | default(company_name) }}"

            # Option fields (same ids you already use)
            customfield_13210:
              id: "{{ urgency_id }}"
            customfield_13204:
              id: "{{ impact_id }}"
            customfield_13657:
              id: "{{ environment_id }}"

            # Insight field (Assets)
            customfield_14503:
              - key: "{{ reporting_service_key }}"

        status_code: [201]
        validate_certs: true
        return_content: true
      register: created

    - name: Print markers for wrapper
      ansible.builtin.debug:
        msg:
          - "ISSUE_KEY={{ created.json.key }}"
          - "ISSUE_URL={{ jira_url }}/browse/{{ created.json.key }}"

