- name: Create SDIMD Service Request via JSM API
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    jira_url: "https://jira.emaratech.ae"
    service_desk_id: "7"
    request_type_id: "94"         # New Service Request to IMD Team
    urgency_id: "13518"           # Medium
    impact_id: "14612"            # Single user
    environment_id: "20707"       # Production
    reporting_service_key: "SD-215"  # emaratechIT.IMD.Unix

  tasks:
    - name: Create Service Request
      ansible.builtin.uri:
        url: "{{ jira_url }}/rest/servicedeskapi/request"
        method: POST
        headers:
          Authorization: "Bearer {{ jira_pat }}"
          Content-Type: "application/json"
          Accept: "application/json"
        body_format: json
        body:
          serviceDeskId: "{{ service_desk_id }}"
          requestTypeId: "{{ request_type_id }}"
          requestFieldValues:
            summary: "{{ summary }}"
            description: "{{ summary }}"
            customfield_13210: { id: "{{ urgency_id }}" }
            customfield_13204: { id: "{{ impact_id }}" }
            customfield_13657: { id: "{{ environment_id }}" }
            customfield_14503:
              - key: "{{ reporting_service_key }}"
        status_code: [201]
        validate_certs: true
        return_content: true
      register: created

    - name: Print markers for wrapper
      ansible.builtin.debug:
        msg:
          - "ISSUE_KEY={{ created.json.issueKey }}"
          - "ISSUE_URL={{ created.json._links.web }}"

